import { Dimensions, StyleSheet } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

export const styles = StyleSheet.create({
  card: { width: screenWidth * 0.92, height: Math.min(screenHeight * 0.74, 620), borderRadius: 20, backgroundColor: '#fff', shadowColor: '#000', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.15, shadowRadius: 12, elevation: 6, overflow: 'hidden' },
  header: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#e5e7eb' },
  title: { fontSize: 22, fontWeight: '700', color: '#111827' },
  company: { fontSize: 15, fontWeight: '600', color: '#4b5563', marginTop: 4 },
  location: { fontSize: 13, color: '#6b7280', marginTop: 2 },
  linkRow: { marginTop: 8, alignSelf: 'flex-start' },
  linkText: { fontSize: 13, fontWeight: '700', color: '#2563eb' },
  body: { flex: 1 },
  bodyContent: { padding: 20, gap: 16 },
  textBlock: { backgroundColor: '#f3f4f6', borderRadius: 14, padding: 14 },
  blockLabel: { fontSize: 12, fontWeight: '700', color: '#6b7280', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 6 },
  blockPreview: { fontSize: 15, lineHeight: 21, color: '#1f2937' },
  answerLabelRow: { flexDirection: 'row', alignItems: 'center' },
  dirtyDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#f59e0b', marginLeft: 8, marginBottom: 6 },
  evaluationRow: { position: 'absolute', right: 16, bottom: 82, zIndex: 2 },
  evaluationBadge: { flexDirection: 'row', alignItems: 'baseline', backgroundColor: '#111827', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 999 },
  evaluationText: { color: '#34d399', fontSize: 18, fontWeight: '800' },
  evaluationSubtext: { color: '#9ca3af', fontSize: 12, marginLeft: 2 },
  actionRow: { flexDirection: 'row' },
  approveButton: { flex: 1, height: 56, backgroundColor: '#2563eb', alignItems: 'center', justifyContent: 'center' },
  approveButtonDone: { backgroundColor: '#16a34a' },
  approveButtonText: { color: '#fff', fontSize: 17, fontWeight: '700' },
  rejectButton: { flex: 1, height: 56, backgroundColor: '#dc2626', alignItems: 'center', justifyContent: 'center' },
  rejectButtonDone: { backgroundColor: '#6b7280' },
  rejectButtonText: { color: '#fff', fontSize: 17, fontWeight: '700' },
  swipeBadge: { position: 'absolute', top: 24, zIndex: 5, paddingHorizontal: 14, paddingVertical: 6, borderRadius: 8, borderWidth: 3 },
  likeBadge: { left: 20, borderColor: '#16a34a', backgroundColor: 'rgba(22, 163, 74, 0.12)', transform: [{ rotate: '-12deg' }] },
  skipBadge: { right: 20, borderColor: '#dc2626', backgroundColor: 'rgba(220, 38, 38, 0.12)', transform: [{ rotate: '12deg' }] },
  swipeBadgeText: { fontSize: 18, fontWeight: '800', color: '#111827', letterSpacing: 1 },
  overlay: { position: 'absolute', inset: 0, backgroundColor: '#fff', zIndex: 10 },
  overlayHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 20, paddingBottom: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#e5e7eb' },
  overlayHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  overlayTitle: { fontSize: 18, fontWeight: '700', color: '#111827' },
  closeButton: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#f3f4f6', alignItems: 'center', justifyContent: 'center', marginLeft: 10 },
  closeButtonText: { fontSize: 15, color: '#374151' },
  saveButton: { backgroundColor: '#111827', paddingHorizontal: 12, paddingVertical: 7, borderRadius: 999 },
  saveButtonText: { color: '#34d399', fontSize: 13, fontWeight: '700' },
  overlayScroll: { flex: 1 },
  overlayScrollContent: { padding: 20 },
  overlayText: { fontSize: 16, lineHeight: 24, color: '#1f2937' },
  answerInput: { fontSize: 16, lineHeight: 24, color: '#1f2937', minHeight: 300 },
});
