#!/usr/bin/env node
"use strict";

/**
 * Builds `.env.local` for Expo from two hand-edited files:
 *
 *   .env             base config that rarely changes: the Apps Script URL
 *                    plus fallback defaults for DATASET / TAB
 *   .env.<profile>   per-dataset overrides: EXPO_PUBLIC_DATASET,
 *                    EXPO_PUBLIC_GOOGLE_SHEETS_TAB
 *
 * Expo CLI natively reads `.env` and `.env.local` (`.env.local` wins), but it
 * ignores custom names like `.env.noit`. `.env` is one of our sources, so the
 * merged result can't be written back into it. It goes to `.env.local`
 * instead, which Expo picks up on its own.
 *
 * The profile always wins over the base for any key present in both.
 *
 * Which profile is used comes from ENV_FILE:
 *   npm start                        -> .env + .env.default
 *   ENV_FILE=.env.noit npm start     -> .env + .env.noit
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const BASE_FILE = ".env";
const OUTPUT_FILE = ".env.local";
const PROFILE_FILE = process.env.ENV_FILE || ".env.default";

if (PROFILE_FILE === BASE_FILE || PROFILE_FILE === OUTPUT_FILE) {
  console.error(
    `[build-env] ENV_FILE can't be ${PROFILE_FILE}: ${BASE_FILE} is the base file ` +
      `and ${OUTPUT_FILE} is the generated output. Use a profile like .env.default or .env.noit.`
  );
  process.exit(1);
}

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const raw = fs.readFileSync(filePath, "utf8");
  const result = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

const basePath = path.join(ROOT, BASE_FILE);
const profilePath = path.join(ROOT, PROFILE_FILE);

if (!fs.existsSync(basePath)) {
  console.warn(
    `[build-env] ${BASE_FILE} not found. Copy .env.example to .env and fill in the Apps Script URL.`
  );
}
if (!fs.existsSync(profilePath)) {
  console.warn(
    `[build-env] ${PROFILE_FILE} not found. Copy .env.YOUR_ENV.example to ${PROFILE_FILE}. ` +
      `Falling back to the defaults from ${BASE_FILE}.`
  );
}

const base = parseEnvFile(basePath);
const profile = parseEnvFile(profilePath);

// Profile overrides base for any key present in both.
const merged = Object.assign({}, base, profile);

const url = merged.EXPO_PUBLIC_GOOGLE_SHEETS_URL || "";
if (!url.startsWith("https://script.google.com/")) {
  console.warn(
    "[build-env] EXPO_PUBLIC_GOOGLE_SHEETS_URL is missing or doesn't look like an Apps Script URL. " +
      "The app will start, but requests to Google Sheets will fail."
  );
}

const lines = [
  "# Generated by scripts/build-env.js — do not edit by hand.",
  `# Source: ${BASE_FILE} + ${PROFILE_FILE}`,
  ...Object.entries(merged).map(([key, value]) => `${key}=${value}`),
  "",
];

fs.writeFileSync(path.join(ROOT, OUTPUT_FILE), lines.join("\n"));
console.log(
  `[build-env] Wrote ${OUTPUT_FILE} from ${BASE_FILE} + ${PROFILE_FILE} (${Object.keys(merged).length} vars)`
);